'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import styles from './page.module.css';

const STOP = new Set('yang dan di ke dari untuk dengan pada dalam ini itu atau karena sebagai oleh akan telah agar juga tidak ada lebih dapat tentang atas antara terhadap saat setelah sebelum masih menjadi sebuah para mereka kami kita the a an and or of to in on for with by from is are was were be been this that as at'.split(/\s+/));
function isoDate(d){return d.toISOString().slice(0,10)}
function daysAgo(n){const d=new Date();d.setDate(d.getDate()-n);return isoDate(d)}
function formatDate(v){if(!v)return '-';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'})}
function topTerms(rows){const c={};for(const r of rows){for(const w of String(r.title||'').toLowerCase().replace(/[^a-z0-9à-ÿ\s-]/gi,' ').split(/\s+/)){if(w.length<4||STOP.has(w))continue;c[w]=(c[w]||0)+1}}return Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,8)}
function csvCell(v){const s=String(v??'');return `"${s.replaceAll('"','""')}"`}

export default function NonSpatialMonitoring(){
  const [companies,setCompanies]=useState([]),[sites,setSites]=useState([]),[company,setCompany]=useState('GROUP'),[customEntity,setCustomEntity]=useState('KPN Plantations'),[areaExtra,setAreaExtra]=useState(''),[start,setStart]=useState(daysAgo(7)),[end,setEnd]=useState(isoDate(new Date())),[extra,setExtra]=useState(''),[language,setLanguage]=useState('indonesian'),[max,setMax]=useState('50'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[data,setData]=useState(null),[tab,setTab]=useState('all');
  useEffect(()=>{(async()=>{if(!supabase)return;const[{data:companyRows},{data:siteRows}]=await Promise.all([supabase.from('companies').select('id,company_code,company_name,region,province,status').eq('status','Active').order('company_code'),supabase.from('sites').select('company_id,site_name,province,location,status').eq('status','Active')]);setCompanies(companyRows||[]);setSites(siteRows||[])})()},[]);
  const selected=companies.find(c=>c.company_code===company);
  const selectedSites=useMemo(()=>selected?sites.filter(s=>s.company_id===selected.id):[],[selected,sites]);
  const areaTerms=useMemo(()=>{
    if(!selected)return[];
    const out=[];
    const add=v=>{const s=String(v||'').trim();if(s&&s.length>=4&&!out.some(x=>x.toLowerCase()===s.toLowerCase()))out.push(s)};
    add(selected.province); add(selected.region);
    for(const s of selectedSites){
      add(s.province); add(s.location);
      const parts=String(s.site_name||'').split(/[-–—]/).map(x=>x.trim());
      if(parts.length>1) add(parts[parts.length-1]);
    }
    return out.slice(0,10);
  },[selected,selectedSites]);
  const entity=company==='GROUP'?'KPN Plantations':company==='CUSTOM'?customEntity:(selected?.company_name||customEntity);
  const code=company==='GROUP'?'KPN':company==='CUSTOM'?'':company;
  const rows=useMemo(()=>data?[...(data.positive||[]),...(data.negative||[]),...(data.needsReview||[])]:[],[data]);
  const visible=tab==='positive'?(data?.positive||[]):tab==='negative'?(data?.negative||[]):tab==='review'?(data?.needsReview||[]):rows;
  const posTerms=useMemo(()=>topTerms(data?.positive||[]),[data]); const negTerms=useMemo(()=>topTerms(data?.negative||[]),[data]);
  const share=data?.totals?.total?Math.round((data.totals.positive/data.totals.total)*100):0;
  async function generate(e){e.preventDefault();setLoading(true);setError('');setData(null);try{const p=new URLSearchParams({start,end,entity,code,extra,language,max,areas:areaTerms.join('||'),areaExtra});const r=await fetch(`/api/non-spatial-monitoring?${p.toString()}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Gagal generate monitoring.');setData(j)}catch(err){setError(err.message||'Gagal generate monitoring.')}finally{setLoading(false)}}
  function exportCsv(){if(!data)return;const lines=[['Sentiment','Tanggal','Judul','Media','Negara Sumber','Bahasa','Search Engine','URL'],...rows.map(r=>[r.sentiment,formatDate(r.seenDate),r.title,r.domain,r.sourceCountry,r.language,r.sourceEngine,r.url])];const csv=lines.map(r=>r.map(csvCell).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Monitoring_Non_Spasial_${start}_${end}.csv`;a.click();URL.revokeObjectURL(a.href)}
  const badgeStyle=s=>s==='positive'?{}:s==='negative'?{}:{background:'#fff4cf',color:'#7a5a00',border:'1px solid #ead48c'};
  return <div className={styles.page}>
    <div className={styles.heading}><div><h1>Monitoring Non Spasial</h1><p>Monitoring pemberitaan berdasarkan periode, entity, alias perusahaan, serta keyword yang dipilih.</p></div></div>
    <section className={styles.panel}><form className={styles.formGrid} onSubmit={generate}>
      <div className={styles.field}><label>Entity / Company</label><select value={company} onChange={e=>setCompany(e.target.value)}><option value="GROUP">KPN Plantations Group</option>{companies.map(c=><option key={c.company_code} value={c.company_code}>{c.company_code} — {c.company_name}</option>)}<option value="CUSTOM">Custom keyword / entity</option></select></div>
      {company==='CUSTOM'&&<div className={styles.field}><label>Custom Entity</label><input value={customEntity} onChange={e=>setCustomEntity(e.target.value)} placeholder="Contoh: KPN Plantations" required/></div>}
      <div className={styles.field}><label>Periode Mulai</label><input type="date" value={start} onChange={e=>setStart(e.target.value)} required/></div><div className={styles.field}><label>Periode Sampai</label><input type="date" value={end} onChange={e=>setEnd(e.target.value)} required/></div>
      <div className={`${styles.field} ${styles.wide}`}><label>Filter Area</label><div style={{padding:'10px 12px',border:'1px solid #d8e2dc',borderRadius:8,background:'#f8fbf9',minHeight:42}}>{company==='GROUP'?'Tidak diterapkan untuk Group':company==='CUSTOM'?'Gunakan Area Tambahan di bawah':areaTerms.length?areaTerms.join(' · '):'Belum ada area di Master Company/Site — pencarian memakai nama legal PT saja'}</div></div><div className={`${styles.field} ${styles.wide}`}><label>Area Tambahan (opsional)</label><input value={areaExtra} onChange={e=>setAreaExtra(e.target.value)} placeholder="Contoh: Ketapang, Sambas, Kubu Raya"/></div><div className={`${styles.field} ${styles.wide}`}><label>Keyword Tambahan (opsional)</label><input value={extra} onChange={e=>setExtra(e.target.value)} placeholder="Contoh: kebakaran OR konflik OR penghargaan"/></div><div className={styles.field}><label>Bahasa Sumber</label><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="indonesian">Indonesia</option><option value="all">Semua bahasa</option></select></div><div className={styles.field}><label>Maks. hasil / kategori</label><select value={max} onChange={e=>setMax(e.target.value)}><option value="25">25</option><option value="50">50</option><option value="100">100</option></select></div>
      <div className={styles.actions}><button className={styles.primary} disabled={loading}>{loading?'Generating…':'Generate Monitoring'}</button></div></form>
      <div className={styles.source}>V8.15.4: pencarian perusahaan menggunakan <strong>nama legal PT + area operasional</strong> dari Master Company & Site. Singkatan perusahaan tidak digunakan. Jika area tersedia, berita harus cocok dengan nama legal PT dan salah satu area yang terdaftar.</div></section>
    {error&&<div className={`${styles.notice} ${styles.error}`}><strong>Monitoring gagal: </strong>{error}</div>}
    {data&&<>
      <div className={`${styles.notice} ${styles.info}`}>Generated untuk <strong>{data.meta.entity}</strong> · {data.meta.start} s.d. {data.meta.end} · {data.totals.total} coverage ditemukan. · Source: <strong>{data.meta.source}</strong><br/>Nama legal PT: {(data.meta.aliases||[]).join(' · ')}<br/>Filter area: {data.meta.areaFilterActive?(data.meta.areas||[]).join(' · '):'Tidak aktif / area belum tersedia'} · Match mode: <strong>{data.meta.matchMode}</strong></div>
      <section className={styles.kpis}><div className={styles.kpi}><span>Total Coverage</span><strong>{data.totals.total}</strong></div><div className={`${styles.kpi} ${styles.positive}`}><span>Positive</span><strong>{data.totals.positive}</strong></div><div className={`${styles.kpi} ${styles.negative}`}><span>Negative</span><strong>{data.totals.negative}</strong></div><div className={styles.kpi}><span>Needs Review</span><strong>{data.totals.needsReview||0}</strong></div></section>
      <section className={styles.panel}><div className={styles.reportActions}><button className={styles.secondary} onClick={()=>window.print()}>Print / Save PDF</button><button className={styles.secondary} onClick={exportCsv}>Download CSV</button></div><div className={styles.insight}><div className={styles.insightBox}><h3>Executive Insight</h3><p>{data.totals.total===0?'Tidak ada coverage yang ditemukan. Coba tambah alias/keyword.':data.totals.negative>data.totals.positive?'Coverage negatif lebih dominan. Prioritaskan review headline negatif dan artikel Needs Review.':data.totals.positive>data.totals.negative?'Coverage positif lebih dominan, namun artikel Needs Review tetap perlu diperiksa agar isu reputasi tidak terlewat.':'Coverage positif dan negatif relatif seimbang.'}</p><p>Positive: {data.totals.positive} · Negative: {data.totals.negative} · Needs review: {data.totals.needsReview||0} · Positive share: {share}%.</p></div><div className={styles.insightBox}><h3>Headline Themes</h3><p>Positive themes</p><div className={styles.topics}>{posTerms.length?posTerms.map(([t,n])=><span className={styles.topic} key={t}>{t} · {n}</span>):<span className={styles.topic}>No recurring theme</span>}</div><p>Negative themes</p><div className={styles.topics}>{negTerms.length?negTerms.map(([t,n])=><span className={styles.topic} key={t}>{t} · {n}</span>):<span className={styles.topic}>No recurring theme</span>}</div></div></div></section>
      <section className={styles.panel}><div className={styles.tabs}><button className={`${styles.tab} ${tab==='all'?styles.active:''}`} onClick={()=>setTab('all')}>All ({rows.length})</button><button className={`${styles.tab} ${tab==='positive'?styles.active:''}`} onClick={()=>setTab('positive')}>Positive ({data.totals.positive})</button><button className={`${styles.tab} ${tab==='negative'?styles.active:''}`} onClick={()=>setTab('negative')}>Negative ({data.totals.negative})</button><button className={`${styles.tab} ${tab==='review'?styles.active:''}`} onClick={()=>setTab('review')}>Needs Review ({data.totals.needsReview||0})</button></div>{visible.length?<div className={styles.articleGrid}>{visible.map((r,i)=><article className={styles.article} key={`${r.url}-${i}`}><div className={styles.articleTop}><span style={badgeStyle(r.sentiment)} className={`${styles.badge} ${r.sentiment==='positive'?styles.badgePos:r.sentiment==='negative'?styles.badgeNeg:''}`}>{r.sentiment==='needs_review'?'needs review':r.sentiment}</span><span className={styles.meta}>{formatDate(r.seenDate)}</span></div><h3>{r.title}</h3><div className={styles.meta}><span>{r.domain||'Unknown source'}</span><span>{r.sourceEngine||''}</span><span>{r.sourceCountry||''}</span></div>{r.url&&<a className={styles.link} href={r.url} target="_blank" rel="noreferrer">Open article ↗</a>}</article>)}</div>:<div className={styles.empty}>Tidak ada artikel pada kategori ini.</div>}</section>
    </>}
  </div>
}
