-- =========================================================
-- SMD V8.20 - AUDIT TRAIL / CHANGE HISTORY
-- Run once in Supabase SQL Editor after the app deploy.
-- Captures INSERT / UPDATE / DELETE on key sustainability tables.
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text,
  company_id uuid references public.companies(id) on delete set null,
  operation text not null check (operation in ('INSERT','UPDATE','DELETE')),
  changed_at timestamptz not null default now(),
  changed_by uuid,
  changed_by_email text,
  old_data jsonb,
  new_data jsonb,
  changed_fields jsonb
);

create index if not exists idx_audit_log_changed_at on public.audit_log(changed_at desc);
create index if not exists idx_audit_log_company on public.audit_log(company_id, changed_at desc);
create index if not exists idx_audit_log_table on public.audit_log(table_name, changed_at desc);

alter table public.audit_log enable row level security;
drop policy if exists audit_log_authenticated_select on public.audit_log;
create policy audit_log_authenticated_select on public.audit_log
for select to authenticated using (true);

grant select on public.audit_log to authenticated;

create or replace function public.smd_jsonb_changed_fields(old_row jsonb, new_row jsonb)
returns jsonb
language sql
immutable
as $$
  select coalesce(jsonb_object_agg(k, jsonb_build_object('old', old_row->k, 'new', new_row->k)), '{}'::jsonb)
  from (
    select key as k
    from jsonb_object_keys(coalesce(old_row,'{}'::jsonb) || coalesce(new_row,'{}'::jsonb)) key
    where coalesce(old_row,'{}'::jsonb)->key is distinct from coalesce(new_row,'{}'::jsonb)->key
  ) s;
$$;

create or replace function public.smd_resolve_company_id(p_table text, p_data jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_company uuid;
  v_id uuid;
begin
  begin
    if nullif(p_data->>'company_id','') is not null then
      return (p_data->>'company_id')::uuid;
    end if;
  exception when others then
    null;
  end;

  if p_table = 'grievance_actions' then
    begin v_id := nullif(p_data->>'grievance_id','')::uuid; exception when others then v_id := null; end;
    if v_id is not null then select company_id into v_company from public.grievances where id=v_id; end if;
  elsif p_table = 'sims_assessment_items' then
    begin v_id := nullif(p_data->>'assessment_id','')::uuid; exception when others then v_id := null; end;
    if v_id is not null then select company_id into v_company from public.sims_assessments where id=v_id; end if;
  elsif p_table = 'sims_action_plans' then
    begin v_id := nullif(p_data->>'assessment_item_id','')::uuid; exception when others then v_id := null; end;
    if v_id is not null then
      select a.company_id into v_company
      from public.sims_assessment_items i
      join public.sims_assessments a on a.id=i.assessment_id
      where i.id=v_id;
    end if;
  elsif p_table = 'supplier_risk_assessments' then
    begin v_id := nullif(p_data->>'supplier_id','')::uuid; exception when others then v_id := null; end;
    if v_id is not null then select company_id into v_company from public.spatial_suppliers where id=v_id; end if;
  end if;

  return v_company;
end;
$$;

create or replace function public.smd_capture_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old jsonb;
  v_new jsonb;
  v_data jsonb;
  v_record text;
  v_company uuid;
  v_email text;
begin
  if tg_op='INSERT' then
    v_new:=to_jsonb(new); v_data:=v_new;
  elsif tg_op='UPDATE' then
    v_old:=to_jsonb(old); v_new:=to_jsonb(new); v_data:=v_new;
    if v_old = v_new then return new; end if;
  else
    v_old:=to_jsonb(old); v_data:=v_old;
  end if;

  v_record:=coalesce(v_data->>'id', v_data->>'case_id', v_data->>'action_id');
  v_company:=public.smd_resolve_company_id(tg_table_name,v_data);
  begin
    v_email:=auth.jwt()->>'email';
  exception when others then
    v_email:=null;
  end;

  insert into public.audit_log(table_name,record_id,company_id,operation,changed_by,changed_by_email,old_data,new_data,changed_fields)
  values(
    tg_table_name,
    v_record,
    v_company,
    tg_op,
    auth.uid(),
    v_email,
    v_old,
    v_new,
    case when tg_op='UPDATE' then public.smd_jsonb_changed_fields(v_old,v_new) else null end
  );

  if tg_op='DELETE' then return old; else return new; end if;
end;
$$;

-- Install triggers only on tables that exist in this project.
do $$
declare
  t text;
begin
  foreach t in array array[
    'certifications',
    'audit_events',
    'grievances',
    'grievance_actions',
    'sims_assessments',
    'sims_assessment_items',
    'sims_action_plans',
    'spatial_suppliers',
    'supplier_risk_assessments'
  ]
  loop
    if to_regclass('public.'||t) is not null then
      execute format('drop trigger if exists trg_smd_audit_%I on public.%I',t,t);
      execute format('create trigger trg_smd_audit_%I after insert or update or delete on public.%I for each row execute function public.smd_capture_audit_log()',t,t);
    end if;
  end loop;
end $$;

select 'SMD V8.20 audit trail ready' as result;
