-- =========================================================
-- SMD V8.22 - EXECUTIVE RISK HISTORY / MONTHLY SNAPSHOT
-- Run once in Supabase SQL Editor after the app deploy.
-- Stores one monthly Executive Risk snapshot per PT.
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.executive_risk_snapshots (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  snapshot_month date not null,
  score integer not null check (score between 0 and 100),
  risk_level text not null,
  certification_score numeric,
  grievance_action_score numeric,
  sims_score numeric,
  spatial_score numeric,
  weight_certification numeric not null default 25,
  weight_grievance_action numeric not null default 25,
  weight_sims numeric not null default 30,
  weight_spatial numeric not null default 20,
  coverage_available integer not null default 0,
  coverage_total integer not null default 4,
  top_driver text,
  metrics jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, snapshot_month)
);

create index if not exists idx_exec_risk_snapshots_company_month
  on public.executive_risk_snapshots(company_id, snapshot_month desc);

alter table public.executive_risk_snapshots enable row level security;

drop policy if exists exec_risk_snapshot_select on public.executive_risk_snapshots;
create policy exec_risk_snapshot_select on public.executive_risk_snapshots
for select to authenticated using (true);

drop policy if exists exec_risk_snapshot_admin_insert on public.executive_risk_snapshots;
create policy exec_risk_snapshot_admin_insert on public.executive_risk_snapshots
for insert to authenticated
with check (
  lower(coalesce(auth.jwt()->>'email','')) in (
    'ochtoryano.fadhylla@systemmonitoring.local',
    'winengku.pamartajati@systemmonitoring.local',
    'shafiyah.mutiara@systemmonitoring.local',
    'nicky.sudarmantoro@systemmonitoring.local'
  )
);

drop policy if exists exec_risk_snapshot_admin_update on public.executive_risk_snapshots;
create policy exec_risk_snapshot_admin_update on public.executive_risk_snapshots
for update to authenticated
using (
  lower(coalesce(auth.jwt()->>'email','')) in (
    'ochtoryano.fadhylla@systemmonitoring.local',
    'winengku.pamartajati@systemmonitoring.local',
    'shafiyah.mutiara@systemmonitoring.local',
    'nicky.sudarmantoro@systemmonitoring.local'
  )
)
with check (
  lower(coalesce(auth.jwt()->>'email','')) in (
    'ochtoryano.fadhylla@systemmonitoring.local',
    'winengku.pamartajati@systemmonitoring.local',
    'shafiyah.mutiara@systemmonitoring.local',
    'nicky.sudarmantoro@systemmonitoring.local'
  )
);

drop policy if exists exec_risk_snapshot_admin_delete on public.executive_risk_snapshots;
create policy exec_risk_snapshot_admin_delete on public.executive_risk_snapshots
for delete to authenticated
using (
  lower(coalesce(auth.jwt()->>'email','')) in (
    'ochtoryano.fadhylla@systemmonitoring.local',
    'winengku.pamartajati@systemmonitoring.local',
    'shafiyah.mutiara@systemmonitoring.local',
    'nicky.sudarmantoro@systemmonitoring.local'
  )
);

grant select, insert, update, delete on public.executive_risk_snapshots to authenticated;
grant usage, select on sequence public.executive_risk_snapshots_id_seq to authenticated;

-- If V8.20 Audit Trail is already active, include snapshot changes automatically.
do $$
begin
  if to_regprocedure('public.smd_capture_audit_log()') is not null then
    execute 'drop trigger if exists trg_smd_audit_executive_risk_snapshots on public.executive_risk_snapshots';
    execute 'create trigger trg_smd_audit_executive_risk_snapshots after insert or update or delete on public.executive_risk_snapshots for each row execute function public.smd_capture_audit_log()';
  end if;
end $$;

select 'SMD V8.22 executive risk history ready' as result;
