'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase, getSupabaseConfigError } from '../../lib/supabaseClient';
import { daysUntil, formatDate, todayISO } from '../../lib/monitoring';

export default function ActionMonitoring(){
  const [actions,setActions]=useState([]); const [grievances,setGrievances]=useState([]); const [companies,setCompanies]=useState([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('All'); const [priority,setPriority]=useState('All'); const [company,setCompany]=useState('All');
  const [editing,setEditing]=useState(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{loadAll()},[]);
  async function loadAll(){const configError=getSupabaseConfigError();if(configError||!supabase){setError(configError||'Supabase is not configured.');setLoading(false);return}setLoading(true);setError('');const[a,g,c]=await Promise.all([supabase.from('grievance_actions').select('*').order('target_date'),supabase.from('grievances').select('id,case_id,company,site,issue_title,company_id,status'),supabase.from('companies').select('*').order('company_code')]);const e=a.error||g.error||c.error;if(e)setError(e.message);setActions(a.data||[]);setGrievances(g.data||[]);setCompanies(c.data||[]);setLoading(false)}
  const gMap=useMemo(()=>Object.fromEntries(grievances.map(g=>[g.id,g])),[grievances]);
  const filtered=useMemo(()=>actions.filter(a=>{const g=gMap[a.grievance_id]||{};const hay=`${a.action_id} ${a.action_description} ${a.pic||''} ${g.case_id||''} ${g.company||''} ${g.issue_title||''}`.toLowerCase();return hay.includes(search.toLowerCase())&&(status==='All'||a.status===status)&&(priority==='All'||a.priority===priority)&&(company==='All'||g.company_id===company)}),[actions,gMap,search,status,priority,company]);
  const stats=useMemo(()=>({total:filtered.length,open:filtered.filter(a=>a.status!=='Completed').length,overdue:filtered.filter(a=>a.status!=='Completed'&&daysUntil(a.target_date)!==null&&daysUntil(a.target_date)<0).length,completed:filtered.filter(a=>a.status==='Completed').length}),[filtered]);
  async function saveEdit(e){e.preventDefault();if(!supabase||!editing)return;setBusy(true);const statusValue=editing.status;const payload={pic:editing.pic||null,priority:editing.priority,target_date:editing.target_date||null,status:statusValue,progress:statusValue==='Completed'?100:Math.max(0,Math.min(100,Number(editing.progress||0))),completion_date:statusValue==='Completed'?(editing.completion_date||todayISO()):(editing.completion_date||null),remarks:editing.remarks||null};const{error:e2}=await supabase.from('grievance_actions').update(payload).eq('id',editing.id);if(e2)setError(e2.message);else{setEditing(null);await loadAll()}setBusy(false)}
  return <div className="page-wrap"><div className="page-heading"><div><h1>Action Monitoring</h1><p>Central monitoring of all action plans created from grievance cases.</p></div></div>{error?<div className="sync-error"><strong>Supabase error</strong><span>{error}</span></div>:<div className="sync-success">● Action plans are synchronized from Grievance Tracker</div>}
  <section className="kpi-grid"><KPI label="Total Actions" value={loading?'…':stats.total}/><KPI label="Open / Active" value={loading?'…':stats.open}/><KPI label="Overdue" value={loading?'…':stats.overdue}/><KPI label="Completed" value={loading?'…':stats.completed}/></section>
  <section className="panel"><div className="action-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search action, case, company, PIC..."/><select value={company} onChange={e=>setCompany(e.target.value)}><option value="All">All Companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.company_code}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="All">All Priorities</option>{['Critical','High','Medium','Low'].map(v=><option key={v}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="All">All Statuses</option>{['Open','In Progress','Verification','Completed'].map(v=><option key={v}>{v}</option>)}</select></div>
  <div className="table-wrap"><table><thead><tr><th>Action</th><th>Grievance</th><th>Company / Site</th><th>PIC</th><th>Priority</th><th>Target</th><th>Status</th><th>Progress</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="9" className="empty-cell">Loading action plans…</td></tr>:filtered.length?filtered.map(a=>{const g=gMap[a.grievance_id]||{};const overdue=a.status!=='Completed'&&daysUntil(a.target_date)!==null&&daysUntil(a.target_date)<0;return <tr key={a.id}><td><strong>{a.action_id}</strong><div className="muted">{a.action_description}</div></td><td>{g.case_id?<Link className="text-link" href={`/grievances/${g.case_id}`}>{g.case_id}</Link>:'-'}<div className="muted">{g.issue_title||''}</div></td><td>{g.company||'-'}<div className="muted">{g.site||'Company level'}</div></td><td>{a.pic||'-'}</td><td><span className={`badge ${String(a.priority||'Medium').toLowerCase()}`}>{a.priority||'Medium'}</span></td><td>{a.target_date?formatDate(a.target_date):'-'}{overdue?<div className="danger-text">Overdue</div>:null}</td><td><span className="status-pill">{a.status}</span></td><td><div className="progress"><div style={{width:`${Number(a.progress||0)}%`}}></div></div><div className="muted">{Number(a.progress||0)}%</div></td><td><button className="view-btn" onClick={()=>setEditing({...a})}>Edit</button></td></tr>}):<tr><td colSpan="9" className="empty-cell">No action plans found.</td></tr>}</tbody></table></div></section>
  {editing&&<div className="modal-backdrop"><form className="modal-card update-modal" onSubmit={saveEdit}><div className="modal-head"><div><h2>Edit Action — {editing.action_id}</h2><p>Update centralized action status without opening the grievance detail page.</p></div><button type="button" className="icon-btn" onClick={()=>setEditing(null)}>×</button></div><div className="form-grid"><label className="form-field wide"><span>Action</span><input value={editing.action_description||''} disabled/></label><label className="form-field"><span>PIC</span><input value={editing.pic||''} onChange={e=>setEditing({...editing,pic:e.target.value})}/></label><label className="form-field"><span>Priority</span><select value={editing.priority||'Medium'} onChange={e=>setEditing({...editing,priority:e.target.value})}>{['Critical','High','Medium','Low'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-field"><span>Target Date</span><input type="date" value={editing.target_date||''} onChange={e=>setEditing({...editing,target_date:e.target.value})}/></label><label className="form-field"><span>Status</span><select value={editing.status||'Open'} onChange={e=>setEditing({...editing,status:e.target.value})}>{['Open','In Progress','Verification','Completed'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-field"><span>Progress %</span><input type="number" min="0" max="100" value={editing.progress||0} onChange={e=>setEditing({...editing,progress:e.target.value})}/></label><label className="form-field"><span>Completion Date</span><input type="date" value={editing.completion_date||''} onChange={e=>setEditing({...editing,completion_date:e.target.value})}/></label><label className="form-field wide"><span>Remarks</span><textarea value={editing.remarks||''} onChange={e=>setEditing({...editing,remarks:e.target.value})}/></label></div><div className="form-actions"><div></div><div className="form-action-right"><button type="button" className="secondary-btn" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Saving…':'Save Action'}</button></div></div></form></div>}
  </div>}
function KPI({label,value}){return <div className="kpi-card"><span>{label}</span><strong>{value}</strong></div>}
